[package]
name = "atoma-backends"
version.workspace = true
edition.workspace = true

[dependencies]
atoma-vllm-backend = { path = "vllm", optional = true }
serde = { workspace = true, features = ["derive"] }

[features]
vllm = ["dep:atoma-vllm-backend"]
nccl = ["atoma-vllm-backend/nccl"]
